import { Tour, Guide, TourAvailability } from '@/types';

// ─── Guides ──────────────────────────────────────────────────
export const MOCK_GUIDES: Guide[] = [
  {
    id: 'g1',
    name: 'Juan Palavecino',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format',
    rating: 4.97,
    toursCount: 312,
    verified: true,
    bio: 'Salteño de toda la vida. Licenciado en Turismo con 8 años guiando visitantes por el NOA. Apasionado por la historia colonial y la cultura andina.',
    languages: ['Español', 'Inglés', 'Portugués'],
    whatsapp: '+5493874123456',
  },
  {
    id: 'g2',
    name: 'Valentina Chocobar',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&auto=format',
    rating: 4.94,
    toursCount: 187,
    verified: true,
    bio: 'Jujeña, descendiente de comunidades originarias. Guía certificada por el INPROTUR. Especialista en turismo cultural y sostenible.',
    languages: ['Español', 'Inglés'],
    whatsapp: '+5493885654321',
  },
  {
    id: 'g3',
    name: 'Rodrigo Mamani',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&auto=format',
    rating: 4.91,
    toursCount: 245,
    verified: true,
    bio: 'Guía de montaña certificado UIAGM. 10 años llevando expediciones por la Puna, Quebrada y Yungas. Instructor de kayak y parapente.',
    languages: ['Español', 'Inglés', 'Quechua'],
    whatsapp: '+5493874987654',
  },
  {
    id: 'g4',
    name: 'Lucía Orellana',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&auto=format',
    rating: 4.88,
    toursCount: 143,
    verified: true,
    bio: 'Especialista en ecoturismo y naturaleza del NOA. Bióloga y guía certificada. Conoce cada sendero y especie de la región.',
    languages: ['Español', 'Inglés', 'Alemán'],
    whatsapp: '+5493874555666',
  },
];

// ─── Availability helpers ─────────────────────────────────────
const nextDates = (days: number[]): TourAvailability[] => {
  const base = new Date();
  return days.map((offset) => {
    const d = new Date(base);
    d.setDate(base.getDate() + offset);
    const dateStr = d.toISOString().split('T')[0];
    return {
      date: dateStr,
      guides: offset % 3 === 0
        ? [MOCK_GUIDES[0], MOCK_GUIDES[1]]
        : offset % 2 === 0
          ? [MOCK_GUIDES[0], MOCK_GUIDES[2]]
          : [MOCK_GUIDES[1]],
    };
  });
};

// ─── Free Walking Tours ───────────────────────────────────────
export const FREE_TOURS: Tour[] = [
  {
    id: 'fwt-salta',
    slug: 'free-walking-tour-salta-capital',
    title: 'Free Walking Tour Salta Capital',
    type: 'free',
    category: 'ciudad',
    tags: ['Historia', 'Arquitectura', 'Colonial', 'Cultura'],
    price: null,
    priceMin: 15000,
    priceMax: 20000,
    priceCurrency: 'ARS',
    duration: 2.5,
    minParticipants: 1,
    maxParticipants: 20,
    languages: ['Español', 'Inglés'],
    location: 'Salta Capital',
    city: 'Salta',
    meetingPoint: 'Plaza 9 de Julio',
    meetingPointDescription: 'Nos encontramos frente a la Catedral Basílica de Salta, en la esquina de España y Caseros. El guía llevará un paraguas naranja.',
    shortDescription: 'Recorremos los rincones más icónicos del casco histórico de Salta. Dos horas y media de historia, arquitectura colonial y anécdotas únicas.',
    description: `Salta "La Linda" tiene mucho para contar, y este tour te lo cuenta todo. Caminamos por el corazón colonial de la ciudad, explorando cada plaza, iglesia y callejón con historias que no encontrarás en ningún libro de texto.\n\nComenzamos en la monumental Plaza 9 de Julio, rodeada por edificios históricos que definen la identidad de la ciudad. Visitamos la Catedral Basílica con su famosa Señor del Milagro, el Cabildo histórico (hoy Museo), y el imponente Convento San Bernardo.\n\nNuestro recorrido incluye el Paseo Güemes, los mercados tradicionales del centro, y terminamos con una vista panorámica desde el Cerro San Bernardo. Durante el tour, compartimos la historia de la batalla de Salta, la vida cotidiana colonial y las tradiciones vigentes hasta hoy.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/casahistorica_nrxunv4s_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/listas/casahi_skifgon3_10-09-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/sender_vmhg5vte_16-07-2025.jpg',
    ],
    guides: [MOCK_GUIDES[0], MOCK_GUIDES[1]],
    rating: 4.97,
    reviewCount: 340,
    itinerary: [
      { order: 1, time: '09:00', title: 'Encuentro en Plaza 9 de Julio', description: 'Presentación del guía y del grupo. Breve introducción histórica de Salta.' },
      { order: 2, time: '09:20', title: 'Catedral Basílica & Museo Cabildo', description: 'Exploramos los dos edificios más emblemáticos de la plaza y su historia colonial.' },
      { order: 3, time: '09:55', title: 'Convento San Bernardo', description: 'El convento colonial más antiguo de Salta, con su puerta de madera tallada única.' },
      { order: 4, time: '10:25', title: 'Barrio Histórico & Casas Coloniales', description: 'Calles adoquinadas y casonas del siglo XVIII en el corazón del casco histórico.' },
      { order: 5, time: '10:50', title: 'Mercado Central', description: 'El corazón del comercio local. Empanadas, alfajores y artesanías del NOA.' },
      { order: 6, time: '11:20', title: 'Mirador Cerro San Bernardo', description: 'Vista panorámica de toda la ciudad. Final del tour y momento del donativo voluntario.' },
    ],
    includes: ['Guía profesional certificado', 'Mapas del recorrido', 'Información de puntos de interés adicionales'],
    excludes: ['Entradas a museos', 'Comidas o bebidas', 'Transporte'],
    accessibility: 'Recorrido completamente accesible para sillas de ruedas y coches de bebé. Sin escaleras obligatorias.',
    petsAllowed: true,
    groupsAllowed: true,
    additionalExpenses: 'Entrada al Teleférico Cerro San Bernardo: $3.500 ARS (opcional). Entradas a museos: $1.000-$2.500 ARS (opcionales).',
    paymentMethods: ['Efectivo ARS', 'Transferencia bancaria', 'MercadoPago'],
    freeCancellation: true,
    availability: nextDates([1, 2, 3, 5, 6, 7, 8, 10, 12]),
    whatsappLink: 'https://wa.me/5493874123456?text=Hola!+Quiero+reservar+el+Free+Tour+Salta+Capital',
  },
  {
    id: 'fwt-jujuy',
    slug: 'free-walking-tour-jujuy',
    title: 'Free Walking Tour San Salvador de Jujuy',
    type: 'free',
    category: 'ciudad',
    tags: ['Historia', 'Independencia', 'Colonial', 'Cultura Andina'],
    price: null,
    priceMin: 15000,
    priceMax: 20000,
    priceCurrency: 'ARS',
    duration: 2,
    minParticipants: 1,
    maxParticipants: 18,
    languages: ['Español', 'Inglés'],
    location: 'San Salvador de Jujuy',
    city: 'Jujuy',
    meetingPoint: 'Plaza Belgrano',
    meetingPointDescription: 'Frente a la estatua del General Belgrano, en la plaza principal. El guía llevará una bandera naranja de NorteWalk.',
    shortDescription: 'El tour que cuenta la historia de la Independencia Argentina desde sus protagonistas. Recorremos la ciudad que vio nacer la Jura de la Independencia.',
    description: `San Salvador de Jujuy guarda uno de los capítulos más apasionantes de la Independencia Argentina. Este tour revela esos secretos con la pasión de quien ha crecido entre estas calles.\n\nDesde la emblemática Plaza Belgrano y su Cabildo histórico —donde se juró la primera Constitución— hasta la Catedral Basílica que guarda un dosel tallado en madera única en Latinoamérica. Visitamos el Museo Histórico Provincial y recorremos el barrio histórico con sus mercados de artesanías.\n\nUn tour imperdible para entender la riqueza cultural del NOA, donde conviven la tradición española colonial, la herencia indígena y el espíritu independentista.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/listas/casahi_skifgon3_10-09-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/casahistorica_nrxunv4s_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/casade_pmtlzb9l_16-07-2025.jpeg',
    ],
    guides: [MOCK_GUIDES[1], MOCK_GUIDES[0]],
    rating: 4.94,
    reviewCount: 218,
    itinerary: [
      { order: 1, time: '10:00', title: 'Plaza Belgrano & Cabildo', description: 'El epicentro histórico. Aquí se juró la primera Constitución argentina.' },
      { order: 2, time: '10:25', title: 'Catedral Basílica', description: 'El tesoro arquitectónico: el único dosel de madera tallada de América.' },
      { order: 3, time: '10:55', title: 'Casa de Gobierno & Éxodo Jujeño', description: 'La historia de la evacuación más heroica de la Guerra de la Independencia.' },
      { order: 4, time: '11:20', title: 'Mercado Artesanal', description: 'Textiles andinos, cerámicas y productos locales del verdadero NOA.' },
      { order: 5, time: '11:45', title: 'Barrio Cultural', description: 'Murales, galerías y el espíritu vivo de Jujuy en sus calles artísticas.' },
    ],
    includes: ['Guía profesional certificado', 'Material informativo del recorrido'],
    excludes: ['Entradas a museos', 'Comidas y bebidas'],
    accessibility: 'La mayor parte del recorrido es accesible. Una sección tiene adoquines irregulares.',
    petsAllowed: true,
    groupsAllowed: true,
    additionalExpenses: 'Museo Histórico: $2.000 ARS. Museo Arqueológico: $1.500 ARS.',
    paymentMethods: ['Efectivo ARS', 'Transferencia bancaria', 'MercadoPago'],
    freeCancellation: true,
    availability: nextDates([1, 2, 4, 5, 7, 9, 11]),
    whatsappLink: 'https://wa.me/5493885654321?text=Hola!+Quiero+reservar+el+Free+Tour+Jujuy',
  },
  {
    id: 'fwt-quebrada',
    slug: 'free-tour-quebrada-humahuaca',
    title: 'Free Tour Quebrada de Humahuaca',
    type: 'free',
    category: 'ciudad',
    tags: ['Patrimonio UNESCO', 'Cultura Andina', 'Arte Rupestre', 'Naturaleza'],
    price: null,
    priceMin: 18000,
    priceMax: 25000,
    priceCurrency: 'ARS',
    duration: 3,
    minParticipants: 2,
    maxParticipants: 15,
    languages: ['Español', 'Inglés', 'Quechua'],
    location: 'Quebrada de Humahuaca, Jujuy',
    city: 'Humahuaca',
    meetingPoint: 'Plaza Principal de Humahuaca',
    meetingPointDescription: 'Frente a la famosa escultura del Indio Victorioso en la Plaza Central de Humahuaca. Tour que recorre el pueblo y sus alrededores.',
    shortDescription: 'Un recorrido por el corazón de la Quebrada Patrimonio UNESCO. Historia, arte rupestre, iglesias coloniales y los colores imposibles de la montaña andina.',
    description: `La Quebrada de Humahuaca es Patrimonio de la Humanidad UNESCO, y este tour hace justicia a esa distinción. Con Rodrigo —guía de raíces locales— descubrimos el alma de este lugar único.\n\nRecorremos el pueblo histórico de Humahuaca con su iglesia colonial del siglo XVII, el cabildo y la famosa escultura del Indio Victorioso que da la hora cada mediodía. Visitamos los talleres de artistas locales y el mercado de artesanías.\n\nEn las afueras del pueblo, llegamos a los cerros de colores para ver de cerca la paleta geológica que hace famosa a esta región: rojos, amarillos, violetas y verdes. Al atardecer, el espectáculo es sencillamente único en el mundo.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/sender_vmhg5vte_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/casade_pmtlzb9l_16-07-2025.jpeg',
      'https://www.tucumanturismo.gob.ar/public/img/casahistorica_nrxunv4s_16-07-2025.jpg',
    ],
    guides: [MOCK_GUIDES[2], MOCK_GUIDES[1]],
    rating: 4.98,
    reviewCount: 156,
    itinerary: [
      { order: 1, time: '11:00', title: 'Plaza Central & El Indio Victorioso', description: 'La escultura más famosa de la Quebrada y el reloj solar del cabildo colonial.' },
      { order: 2, time: '11:30', title: 'Iglesia de Nuestra Señora de la Candelaria', description: 'Joya del arte colonial andino del siglo XVII. Interior con pinturas y tallas únicas.' },
      { order: 3, time: '12:00', title: 'Talleres & Mercado Artesanal', description: 'Conocemos a artistas locales. Textiles, cerámica y platería andina genuina.' },
      { order: 4, time: '12:30', title: 'Cerros de Colores', description: 'Las formaciones geológicas que pintan la Quebrada con 14 colores distintos.' },
      { order: 5, time: '13:30', title: 'Cierre & Donativo', description: 'Punto panorámico final. Momento del donativo voluntario y agradecimiento.' },
    ],
    includes: ['Guía certificado bilingüe', 'Información histórica impresa', 'Agua mineral'],
    excludes: ['Transporte desde/hacia Jujuy', 'Entradas', 'Almuerzo'],
    accessibility: 'La parte en los cerros requiere caminar por terreno irregular. No apto para movilidad reducida en esa sección.',
    petsAllowed: false,
    groupsAllowed: true,
    additionalExpenses: 'Almuerzo en mercado local: $4.000-$8.000 ARS. Transporte Jujuy-Humahuaca: $2.500 ARS.',
    paymentMethods: ['Efectivo ARS', 'Transferencia', 'MercadoPago'],
    freeCancellation: true,
    availability: nextDates([2, 3, 5, 6, 9, 10, 13]),
    whatsappLink: 'https://wa.me/5493874987654?text=Hola!+Quiero+reservar+el+Free+Tour+Quebrada+de+Humahuaca',
  },
];

// ─── Paid Active Tourism Tours ────────────────────────────────
export const PAID_TOURS: Tour[] = [
  // AIRE
  {
    id: 'exc-parapente-salta',
    slug: 'parapente-salta-cerro-20-enero',
    title: 'Parapente en Salta — Cerro 20 de Enero',
    type: 'paid',
    category: 'aire',
    tags: ['Parapente', 'Adrenalina', 'Vuelo', 'Salta Capital'],
    price: 85000,
    priceCurrency: 'ARS',
    duration: 0.5,
    difficulty: 'facil',
    minParticipants: 1,
    maxParticipants: 6,
    languages: ['Español', 'Inglés'],
    location: 'Cerro 20 de Enero, Salta',
    city: 'Salta',
    meetingPoint: 'Base Cerro 20 de Enero',
    meetingPointDescription: 'Acceso por Av. Tavella, al final de la calle. GPS: -24.8008, -65.4059. Llegar 20 min antes.',
    shortDescription: 'Volá en parapente sobre Salta la Linda. Vista de 360° de la ciudad, la Quebrada de los Pablos y el Valle de Lerma. Vuelo en tándem con instructor certificado FAP.',
    description: `El parapente sobre Salta es una de esas experiencias que redefinen el viaje. Desde el Cerro 20 de Enero, con más de 500 metros de vuelo sobre el nivel de la ciudad, el Valle de Lerma se despliega como un mapa viviente bajo tus pies.\n\nEl vuelo es en tándem con Rodrigo, instructor certificado por la Federación Argentina de Parapente (FAP) con más de 1.200 vuelos. No necesitás experiencia previa: simplemente corré unos pasos y el viento hace el resto.\n\nEn el aire, el instructor puede realizar maniobras suaves o más emocionantes según tu preferencia. El vuelo dura entre 20 y 30 minutos dependiendo las condiciones del viento. Incluye GoPro y fotos del despegue.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/parapente1_s0ul3h7p_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/rappel_g189d4yq_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/sender_vmhg5vte_16-07-2025.jpg',
    ],
    guides: [MOCK_GUIDES[2]],
    rating: 4.95,
    reviewCount: 204,
    itinerary: [
      { order: 1, time: '08:30', title: 'Recepción y briefing de seguridad', description: 'Presentación del equipo, repaso de posición de vuelo y señales.' },
      { order: 2, time: '09:00', title: 'Equipamiento y despegue', description: 'Arnés, casco y conexión al parapente. 3 pasos y estás volando.' },
      { order: 3, time: '09:05', title: 'Vuelo en tándem', description: '20-30 minutos sobrevolando Salta a 2.200 msnm. Vista 360° del Valle de Lerma.' },
      { order: 4, time: '09:35', title: 'Aterrizaje y entrega de fotos/video', description: 'Aterrizaje suave en zona habilitada. Fotos y video vía WhatsApp o USB.' },
    ],
    includes: ['Vuelo en tándem con instructor certificado FAP', 'Equipo completo (arnés, casco)', 'Video y fotos del vuelo', 'Seguro de vuelo'],
    excludes: ['Transporte al cerro', 'Comidas'],
    accessibility: 'Peso mínimo 40 kg, máximo 110 kg. No apto para personas con problemas cardíacos o vértigo severo.',
    petsAllowed: false,
    groupsAllowed: true,
    additionalExpenses: 'Transporte remis al cerro: $5.000 ARS aprox.',
    paymentMethods: ['Efectivo ARS', 'Transferencia', 'MercadoPago', 'WhatsApp'],
    freeCancellation: true,
    availability: nextDates([1, 3, 4, 6, 7, 10, 11]),
    whatsappLink: 'https://wa.me/5493874987654?text=Hola!+Quiero+reservar+Parapente+en+Salta',
  },
  {
    id: 'exc-tirolesa-yungas',
    slug: 'tirolesa-canopy-yungas-salta',
    title: 'Tirolesa & Canopy en las Yungas',
    type: 'paid',
    category: 'aire',
    tags: ['Tirolesa', 'Canopy', 'Yungas', 'Adrenalina'],
    price: 45000,
    priceCurrency: 'ARS',
    duration: 3,
    difficulty: 'facil',
    minParticipants: 2,
    maxParticipants: 10,
    languages: ['Español'],
    location: 'Yungas Salteñas, Ruta Nacional 68',
    city: 'Salta',
    meetingPoint: 'Centro Yungas Adventure, Km 54 RN68',
    meetingPointDescription: 'Km 54 de la Ruta Nacional 68, pasando El Carril. Acceso por portón naranja.',
    shortDescription: 'Cinco tirolesas sobre el canopy de la selva de yungas. La adrenalina de volar sobre la copa de los árboles en uno de los ecosistemas más biodiversos de Argentina.',
    description: `Las Yungas salteñas forman parte de la ecorregión más biodiversa de Argentina, y la mejor manera de verla es... por arriba. Este circuito de 5 tirolesas te lleva sobre la copa de los árboles, cruzando quebradas y vistas que son sencillamente imposibles desde el suelo.\n\nEl circuito dura 3 horas e incluye tirolesas de hasta 250 metros de longitud y 40 metros de altura. Apto para toda la familia: mínimo 12 años y 30 kg de peso.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/rappel_g189d4yq_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/parapente1_s0ul3h7p_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/mounta_d28pzfuo_16-07-2025.jpg',
    ],
    guides: [MOCK_GUIDES[2], MOCK_GUIDES[3]],
    rating: 4.88,
    reviewCount: 97,
    itinerary: [
      { order: 1, time: '09:00', title: 'Llegada y equipamiento', description: 'Charla de seguridad, arnés y casco. Introducción a la flora de Yungas.' },
      { order: 2, time: '09:30', title: 'Tirolesas 1 y 2 — Valle bajo', description: '120 m y 180 m sobre el río. Vista de helechos gigantes y selva subtropical.' },
      { order: 3, time: '10:15', title: 'Tirolesas 3, 4 y 5 — Canopy alto', description: 'Las tres tirolesas más largas: hasta 250 m de vuelo sobre la copa de los árboles.' },
      { order: 4, time: '11:30', title: 'Senderito de regreso', description: 'Bajada a pie por el sendero guiado con interpretación de flora y fauna.' },
    ],
    includes: ['5 tirolesas guiadas', 'Equipo completo', 'Seguro de actividad', 'Guía naturalista'],
    excludes: ['Transporte', 'Comidas', 'Fotografías profesionales'],
    accessibility: 'Mínimo 12 años. Peso entre 30 y 120 kg. No apto para embarazadas.',
    petsAllowed: false,
    groupsAllowed: true,
    additionalExpenses: 'Fotos profesionales del circuito: $15.000 ARS.',
    paymentMethods: ['Efectivo ARS', 'Transferencia', 'MercadoPago'],
    freeCancellation: true,
    availability: nextDates([2, 4, 5, 7, 9, 12]),
    whatsappLink: 'https://wa.me/5493874987654?text=Hola!+Quiero+reservar+Tirolesa+Yungas',
  },
  // AGUA
  {
    id: 'exc-kayak-cabra-corral',
    slug: 'kayak-dique-cabra-corral',
    title: 'Kayak en el Dique Cabra Corral',
    type: 'paid',
    category: 'agua',
    tags: ['Kayak', 'Lago', 'Naturaleza', 'Relajante'],
    price: 38000,
    priceCurrency: 'ARS',
    duration: 3.5,
    difficulty: 'facil',
    minParticipants: 1,
    maxParticipants: 12,
    languages: ['Español', 'Inglés'],
    location: 'Dique Cabra Corral, Salta',
    city: 'Salta',
    meetingPoint: 'Club Náutico Cabra Corral',
    meetingPointDescription: 'Acceso por Ruta Provincial 47, km 8. El Club Náutico está indicado con carteles. 1hs 20min desde Salta Capital.',
    shortDescription: 'El espejo de agua más grande del NOA, rodeado de sierras rojizas. Un kayak al atardecer en el Dique Cabra Corral es una postal que no tiene precio.',
    description: `El Dique Cabra Corral es el embalse más grande del noroeste argentino, y uno de los destinos naturales más impresionantes de Salta. Rodeado de sierras de color rojo intenso, el espejo de agua calma que forma el dique es perfecta para el kayak, incluso para quienes nunca han remado.\n\nLa excursión combina dos horas de kayak guiado con un picnic a orillas del lago. Navegamos por brazos del embalse donde la fauna es abundante: garzas, cormoranes, carpinchos y a veces cóndores sobrevolando las sierras.\n\nEl tour tiene opciones para kayak simple o doble, y el guía enseña la técnica básica en tierra antes de lanzarse al agua. Apto para toda la familia desde 8 años.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/_MG_6030-Editar_h34gutlm_16-01-2026.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/mounta_d28pzfuo_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/sender_vmhg5vte_16-07-2025.jpg',
    ],
    guides: [MOCK_GUIDES[2], MOCK_GUIDES[3]],
    rating: 4.92,
    reviewCount: 173,
    itinerary: [
      { order: 1, time: '15:00', title: 'Llegada y clase de remo', description: 'Recepción en el club náutico. Instrucción básica de remo y seguridad.' },
      { order: 2, time: '15:30', title: 'Kayak guiado — Brazo norte', description: 'Navegamos el brazo norte, con vistas a las Sierras de Muñano. Avistaje de fauna.' },
      { order: 3, time: '17:00', title: 'Picnic & Atardecer', description: 'Orilla desembarcamos para el picnic mientras el sol pinta de naranja las sierras rojas.' },
      { order: 4, time: '18:30', title: 'Regreso y cierre', description: 'Vuelta al club náutico. Foto grupal. Cierre del tour.' },
    ],
    includes: ['Kayak simple o doble', 'Chaleco salvavidas y remo', 'Guía acuático certificado', 'Picnic orillero (fruta, agua, snacks)', 'Seguro de actividad'],
    excludes: ['Transporte desde Salta', 'Almuerzo previo'],
    accessibility: 'Mínimo 8 años. Saber nadar es recomendable. Peso máximo por kayak: 130 kg.',
    petsAllowed: false,
    groupsAllowed: true,
    additionalExpenses: 'Transporte desde Salta Capital: $12.000 ARS (consultar combos).',
    paymentMethods: ['Efectivo ARS', 'Transferencia', 'MercadoPago'],
    freeCancellation: true,
    availability: nextDates([1, 2, 4, 5, 6, 8, 10, 11]),
    whatsappLink: 'https://wa.me/5493874987654?text=Hola!+Quiero+reservar+Kayak+Dique+Cabra+Corral',
  },
  {
    id: 'exc-rafting-juramento',
    slug: 'rafting-rio-juramento-salta',
    title: 'Rafting en el Río Juramento',
    type: 'paid',
    category: 'agua',
    tags: ['Rafting', 'Río', 'Adrenalina', 'Grupo'],
    price: 65000,
    priceCurrency: 'ARS',
    duration: 4,
    difficulty: 'moderado',
    minParticipants: 4,
    maxParticipants: 8,
    languages: ['Español'],
    location: 'Río Juramento, Salta',
    city: 'Salta',
    meetingPoint: 'Base Rafting Juramento, Km 12',
    meetingPointDescription: 'Km 12 del acceso al Dique Cabra Corral, bajando por el camino de tierra hacia el río. Señalizado.',
    shortDescription: 'Rápidos grado II y III en el Río Juramento. La experiencia de rafting más completa del NOA: adrenalina, naturaleza y un almuerzo en la orilla del río.',
    description: `El Río Juramento, que alimenta al Dique Cabra Corral, ofrece uno de los recorridos de rafting más completos del noroeste argentino. Rápidos de grado II y III, con partes tranquilas donde la belleza del cañón es protagonista.\n\nEl descenso dura aproximadamente 3 horas de río, divididas entre rápidos emocionantes y tramos tranquilos donde podés tirarte al agua o simplemente admirar los cóndores que planean sobre los acantilados. Incluye almuerzo criollo en la orilla.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/_MG_6030-Editar_h34gutlm_16-01-2026.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/rappel_g189d4yq_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/sender_vmhg5vte_16-07-2025.jpg',
    ],
    guides: [MOCK_GUIDES[2]],
    rating: 4.90,
    reviewCount: 88,
    itinerary: [
      { order: 1, time: '08:30', title: 'Base y equipamiento', description: 'Recepción, reparto de equipo y briefing de seguridad en el río.' },
      { order: 2, time: '09:00', title: 'Puesta en el agua — Inicio del descenso', description: 'Los primeros rápidos de calentamiento en el bajo Juramento.' },
      { order: 3, time: '10:30', title: 'Rápidos centrales — Grado III', description: 'Los rápidos más emocionantes. El guía da las instrucciones clave.' },
      { order: 4, time: '11:30', title: 'Almuerzo criollo en la orilla', description: 'Pausa obligada: asado, empanadas y bebidas en la orilla del río.' },
      { order: 5, time: '12:30', title: 'Tramo final & Pull out', description: 'Regreso tranquilo hasta el punto de extracción. Fin del descenso.' },
    ],
    includes: ['Equipo completo (casco, chaleco, neopreno)', 'Guía de río certificado', 'Almuerzo criollo en la orilla', 'Seguro de actividad'],
    excludes: ['Transporte', 'Bebidas adicionales'],
    accessibility: 'Mínimo 14 años. Peso mínimo 50 kg. No apto para personas con problemas de columna, embarazadas o con lesiones recientes.',
    petsAllowed: false,
    groupsAllowed: true,
    additionalExpenses: 'Fotos y video del descenso: $20.000 ARS.',
    paymentMethods: ['Efectivo ARS', 'Transferencia', 'MercadoPago'],
    freeCancellation: true,
    availability: nextDates([3, 5, 7, 10, 12]),
    whatsappLink: 'https://wa.me/5493874987654?text=Hola!+Quiero+reservar+Rafting+Río+Juramento',
  },
  // TIERRA
  {
    id: 'exc-trekking-cardones',
    slug: 'trekking-parque-nacional-cardones-salta',
    title: 'Trekking en el Parque Nacional Los Cardones',
    type: 'paid',
    category: 'tierra',
    tags: ['Trekking', 'Paisaje Andino', 'Flora', 'Fotografía'],
    price: 42000,
    priceCurrency: 'ARS',
    duration: 6,
    difficulty: 'moderado',
    minParticipants: 2,
    maxParticipants: 10,
    languages: ['Español', 'Inglés'],
    location: 'Parque Nacional Los Cardones, Salta',
    city: 'Cachi',
    meetingPoint: 'Centro de Visitantes del Parque',
    meetingPointDescription: 'Ingreso al Parque Nacional Los Cardones, Ruta Provincial 33 entre Payogasta y Cachi. 3hs desde Salta Capital.',
    shortDescription: 'Un trekking de 12 km por el bosque de cardones más espectacular del mundo. Silencio total, altitud andina (3.400 msnm) y una fotogenia que te va a dejar sin palabras.',
    description: `El Parque Nacional Los Cardones protege el bosque de cactus más denso y espectacular de Argentina. Con más de 70.000 cardones — algunos con 200 años de antigüedad— el paisaje que ofrecen estos gigantes verdes contra el fondo de las montañas andinas es absolutamente irreal.\n\nEl trekking de 12 km recorre los senderos principales del parque, pasando por quebradas, vistas panorámicas y zonas arqueológicas. La altitud (3.400 msnm) lo convierte en una actividad de dificultad moderada que requiere buena condición física.\n\nLucía, nuestra guía bióloga, convierte el trekking en una clase magistral de ecología andina: aves de altura, flora endémica y la historia geológica de las montañas que nos rodean.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/sender_vmhg5vte_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/mounta_d28pzfuo_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/casade_pmtlzb9l_16-07-2025.jpeg',
    ],
    guides: [MOCK_GUIDES[3], MOCK_GUIDES[2]],
    rating: 4.93,
    reviewCount: 129,
    itinerary: [
      { order: 1, time: '08:00', title: 'Centro de Visitantes & Briefing', description: 'Registro en el parque. Introducción ecológica de la reserva y el cardón.' },
      { order: 2, time: '08:30', title: 'Sendero Los Puesteros (ida)', description: 'Los primeros 3 km entre cardones centenarios. Avistaje de aves de altura.' },
      { order: 3, time: '10:00', title: 'Mirador Cerro Tin Tin', description: 'Vista de 360°: Valle Calchaquí, Sierras de Muñano y los Andes al fondo.' },
      { order: 4, time: '11:00', title: 'Almuerzo en la montaña', description: 'Pausa para el almuerzo con los cardones como escenario.' },
      { order: 5, time: '12:00', title: 'Sendero de regreso — Ruta alternativa', description: 'Regreso por la quebrada baja, con zona arqueológica y pinturas rupestres.' },
      { order: 6, time: '14:00', title: 'Regreso al Centro de Visitantes', description: 'Cierre del tour. Certificado de participación.' },
    ],
    includes: ['Guía bióloga certificada', 'Almuerzo gourmet en la montaña', 'Entrada al parque nacional', 'Bastones de trekking', 'Botiquín de emergencia'],
    excludes: ['Transporte desde Salta', 'Ropa técnica', 'Protector solar'],
    accessibility: 'Trekking de dificultad moderada a 3.400 msnm. Requiere buena condición física. No apto para personas con problemas cardíacos.',
    petsAllowed: false,
    groupsAllowed: true,
    additionalExpenses: 'Transporte desde Salta Capital: $25.000 ARS (ida y vuelta, consultar combos).',
    paymentMethods: ['Efectivo ARS', 'Transferencia', 'MercadoPago'],
    freeCancellation: true,
    availability: nextDates([2, 4, 6, 9, 11]),
    whatsappLink: 'https://wa.me/5493874555666?text=Hola!+Quiero+reservar+Trekking+Los+Cardones',
  },
  {
    id: 'exc-cabalgata-valles',
    slug: 'cabalgata-valles-calchaquies-salta',
    title: 'Cabalgata por los Valles Calchaquíes',
    type: 'paid',
    category: 'tierra',
    tags: ['Cabalgata', 'Valles Calchaquíes', 'Puesta de sol', 'Gaucho'],
    price: 55000,
    priceCurrency: 'ARS',
    duration: 4,
    difficulty: 'facil',
    minParticipants: 1,
    maxParticipants: 8,
    languages: ['Español', 'Inglés'],
    location: 'Valles Calchaquíes, Cafayate',
    city: 'Cafayate',
    meetingPoint: 'Estancia Los Médanos, Cafayate',
    meetingPointDescription: 'A 5 km del centro de Cafayate por camino de tierra. Acceso por calle Los Viñedos. Señalizado desde la rotonda principal de Cafayate.',
    shortDescription: 'A caballo entre viñedos y quebradas color vino. Los Valles Calchaquíes son, al atardecer, uno de los paisajes más dramáticos de Sudamérica.',
    description: `Montado en un caballo criollo, acompañado por un gaucho local, atravesando viñedos de Torrontés con las quebradas rojizas de fondo y el Nevado de Cachi en el horizonte: pocas experiencias son tan genuinamente "Norte Argentino" como esta cabalgata.\n\nEl recorrido de 4 horas pasa por los viñedos más altos del mundo (1.683 msnm), quebradas naturales y miradores con vista al valle. Al regreso, degustación de vinos locales en la estancia.\n\nLos caballos están perfectamente mantenidos y el guía gaucho adapta el ritmo al nivel de cada jinete. Apto para principiantes totales.`,
    images: [
      'https://www.tucumanturismo.gob.ar/public/img/casade_pmtlzb9l_16-07-2025.jpeg',
      'https://www.tucumanturismo.gob.ar/public/img/sender_vmhg5vte_16-07-2025.jpg',
      'https://www.tucumanturismo.gob.ar/public/img/listas/casahi_skifgon3_10-09-2025.jpg',
    ],
    guides: [MOCK_GUIDES[0], MOCK_GUIDES[3]],
    rating: 4.96,
    reviewCount: 211,
    itinerary: [
      { order: 1, time: '16:00', title: 'Estancia & Asignación de caballos', description: 'Conocés tu caballo y el gaucho te da instrucciones básicas de manejo.' },
      { order: 2, time: '16:30', title: 'Salida entre viñedos', description: 'Los primeros kilómetros entre viñedos de Torrontés al atardecer.' },
      { order: 3, time: '17:30', title: 'Quebrada del Río Calchaquí', description: 'El tramo más fotogénico: paredes rojas de 50 m con el río abajo.' },
      { order: 4, time: '18:30', title: 'Mirador del Valle — Puesta de sol', description: 'El mejor mirador de los Valles Calchaquíes en el momento perfecto del día.' },
      { order: 5, time: '19:30', title: 'Regreso & Degustación de vinos', description: 'Vuelta a la estancia. Degustación de Torrontés y Malbec de altura con el gaucho.' },
    ],
    includes: ['Caballo y equipo de montura', 'Guía gaucho bilingüe', 'Degustación de 3 vinos de la región', 'Merienda en la estancia'],
    excludes: ['Transporte desde Cafayate centro', 'Fotos profesionales'],
    accessibility: 'Apto para principiantes. Peso máximo 100 kg. Mínimo 10 años.',
    petsAllowed: false,
    groupsAllowed: true,
    additionalExpenses: 'Transporte desde Cafayate: $4.000 ARS.',
    paymentMethods: ['Efectivo ARS', 'Transferencia', 'MercadoPago'],
    freeCancellation: true,
    availability: nextDates([1, 2, 3, 4, 5, 6, 8, 9, 10]),
    whatsappLink: 'https://wa.me/5493874123456?text=Hola!+Quiero+reservar+Cabalgata+Valles+Calchaquíes',
  },
];

// ─── All Tours Combined ───────────────────────────────────────
export const ALL_TOURS: Tour[] = [...FREE_TOURS, ...PAID_TOURS];

export function getTourById(id: string): Tour | undefined {
  return ALL_TOURS.find((t) => t.id === id);
}

export function getTourBySlug(slug: string): Tour | undefined {
  return ALL_TOURS.find((t) => t.slug === slug);
}